### PR TITLE
Gps To Entity Added

### PR DESCRIPTION
**Pull request by jakeyboi1**
This adds a Gps To Entity function  to the gps api! This will place a Gps that will track an entity! To use:
VORPutils.Gps:GpsToEntity(entity)

To Remove it just use the already existing RemoveGps api VORPutils.Gps:RemoveGps()

### CODE REVIEW

**Comment by jakeyboi1** [comment]
This may be better off done by. Registering a net event instead of a function. Then making a function to trigger the net event. As of right now this function when ran since it has a loop will not allow any code below where it is triggered to run. This is what I would have done, but I did not see Net Events used anywhere else in the api, so did not know if I should. If that would be ok let me know and I will change it too that!

**Comment by outsider31000** [comment]
this wont work. you cant add an entity that doenst exist within your scope.
that means it only works if the entity is within your scope, the a player is in armadillo and you are in valentine you cant get his entity unless server side and since you cant use this natives in the server side it wouldnt work.

**Comment by jakeyboi1** [comment]
True. This was more so designed just for npc ped entities. I tested this just with a ped spawn, passing the createdped to the function. Have no way of testing this with players, and as such was not meant to work on other players yea.

**Comment by outsider31000** [comment]
its not just with players. its with anything . the entity doesnt exist in your scope therefore onesync removes it = to no id , thats why the entity id always change when you leave the area and comeback onesync puts the entity backagain if its set as mission entity.
this is why we want rpc natives so we can do all this server side.

and also thats why you have netids for this kind of stuff and statebags.

**Comment by jakeyboi1** [comment]
Oh that makes sense, did not know that. Sucks that we can not spawn them server sided. Will close this now lol, appreciate the input, and info.

**Pull request closed without merging**
